[hololens]
package = "emergence/hololens-compass" # expanded to absolute ident in holospec
command = "lens-tree {{ input.hash }}" # GIT_DIR provided in environment -- should be an isolated git-repo with core as alternates? pull/copy result upstream after if it works? use manual copy that decends tree lazily? if no plumbing commands get it done
# pipe job config as JSON into lens by default?

[input]
before = "dwoo-templates" # TODO: delete mockup
root = "site-root"
files = [
    "sass/**",
    "fonts/**",
    "img/**"
]

# optional and stripped from holospec:
[output]
root = "site-root/css" # defaults to hololens.root
merge = "overlay" # overlay / underlay / replace, defaults to overlay
