[hololens]
package = "emergence/hololens-extjs-pages" # expanded to absolute ident in holospec

[input]
after = ["php-classes", "sass", "dwoo-templates"] # TODO: delete mockup
root = "sencha-workspace"
files = [
    "pages/**",
    "packages/**"
]
