[hololens]
package = "holo/lens-mkdocs"
requirements = [
    "fontawesome_markdown",
    "mkdocs-awesome-pages-plugin",
    "mkdocs-macros-plugin",
    "mkdocs-material",
]

[hololens.output]
merge = "replace"
