[hololens]
package = "emergence/hololens-php-classes" # expanded to absolute ident in holospec
command = "lens-tree {{ input.hash }}" # GIT_DIR provided in environment -- should be an isolated git-repo with core as alternates? pull/copy result upstream after if it works? use manual copy that decends tree lazily? if no plumbing commands get it done

[hololens.extra2]
b = 1
a = 2
c = 3

[hololens.extra1]
b = 1
a = 2
c = 3

[input]
files = [
    "php-classes/**/*.php",
    "php-config/**/*.php"
]
