[hololens]
package = "emergence/hololens-php-classes" # expanded to absolute ident in holospec

[hololens.extra2]
b = 1
a = 2
c = 3

[hololens.extra1]
b = 1
a = 2
c = 3

[input]
files = [
    "php-classes/**/*.php",
    "php-config/**/*.php"
]
