[hololens]
package = "emergence/hololens-sass" # expanded to absolute ident in holospec

[input]
before = "dwoo-templates" # TODO: delete mockup
root = "site-root"
files = [
    "sass/**",
    "fonts/**",
    "img/**"
]

# optional and stripped from holospec:
[output]
root = "site-root/css" # defaults to hololens.root
merge = "overlay" # overlay / underlay / replace, defaults to overlay
