[holomapping]
files = [
    "**",

    # filter out legacy asset pools
    "!ext-library/**",
    "!html-templates/app/**",
    "!html-templates/git/**",
    "!html-templates/editor/**",
    "!html-templates/manage/**",
    "!js-library/**",
    "!php-classes/Chaki/**",
    "!php-classes/Sabre/**",
    "!sencha-build/EmergenceContentEditor/production/resources/images/**",
    "!sencha-build/EmergenceEditor/**",
    "!sencha-build/EmergencePullTool/**",
    "!site-root/img/icons/**",
    "!site-root/css/**",
    "!site-root/app.php",
    "!site-root/editor.php",
    "!site-root/emergence-push.php",
    "!site-root/git.php",
    "!site-root/jslib.php",
    "!site-root/manage.php",
    "!site-root/table_manager.php",
    "!site-root/x.php"
]
