[holomapping]
holosource = "extjs"
files = [
    "**/*",
    "!build/",
    "!**/rtl/**",
    "!**/test/**",
    "!classic/theme-aria/**",
    "!classic/theme-classic/**",
    "!classic/theme-classic-sandbox/**",
    "!classic/theme-gray/**",
    "!modern/theme-*/**"
]
