[holosource]
url = "https://github.com/JarvusInnovations/php-markdown.git"
# pin to last commit before PHP version requirement was bumped from 5.3 to 7.4
# a request has been submitted to add a tag/branch ref to the official repo: https://github.com/michelf/php-markdown/issues/364
# until then, a fork is used to tag a pre-2.0 release
ref = "refs/tags/1.10.0"
