name: Projections

on:
  push:
    tags:
      - 'v1.*'


jobs:
  holobranch-projections:
    runs-on: ubuntu-latest
    steps:
    - name: 'Update holobranch: emergence/skeleton/v1'
      uses: JarvusInnovations/hologit@actions/projector/v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HAB_LICENSE: accept
      with:
        ref: releases/v1
        holobranch: emergence-skeleton
        commit-to: emergence/skeleton/v1
    - name: 'Update holobranch: emergence/vfs-site/v1'
      uses: JarvusInnovations/hologit@actions/projector/v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HAB_LICENSE: accept
      with:
        ref: releases/v1
        holobranch: emergence-vfs-site
        commit-to: emergence/vfs-site/v1
    - name: 'Update skeleton-v1.emr.ge'
      env:
        VFS_DEV_TOKEN: ${{ secrets.VFS_DEV_TOKEN }}
      run: |
        # pull latest commit
        curl -X POST \
          --silent \
          --fail \
          -H "Authorization: Token ${VFS_DEV_TOKEN}" \
          -H "Accept: application/json" \
          "http://skeleton-v1.emr.ge/site-admin/sources/emergence-skeleton-v1/pull?fetch=true" \
          | jq '.'

        # sync VFS to git
        curl -X POST \
          --silent \
          --fail \
          -H "Authorization: Token ${VFS_DEV_TOKEN}" \
          -H "Accept: application/json" \
          "http://skeleton-v1.emr.ge/site-admin/sources/emergence-skeleton-v1/sync-to-vfs" \
          | jq '.'
